version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'book'
    ports:
      - "5432:5432"
  app:
    image: example-docker-compose
    ports:
      - "8080:8080"
    network_mode: host
